const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node { constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners={};this.dataset={};this.classList={add(){},toggle(){}};this.elements={};this.attributes={};this.hidden=false;this.value='';this.style={};}append(...n){this.children.push(...n)}prepend(...n){this.children.unshift(...n)}replaceChildren(...n){this.children=n}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,f){this.listeners[k]=f}querySelector(){return null}querySelectorAll(){return []}scrollIntoView(){}focus(){} }
const form=new Node('form');for(let n of ['q','state','from','month','category','age','access','format','cost','dateRange'])form.elements[n]=new Node('select');const keys=['.event-list','.event-month-view','.event-summary','.event-empty','.event-error','[data-event-watchlist]','[data-organizer-directory]','[data-refresh-note]'];const map=Object.fromEntries(keys.map(x=>[x,new Node()]));map['form']=form;
const root=new Node();root.querySelector=s=>map[s]||null;const stateBox=new Node();const doc={querySelector:s=>s==='[data-events]'?root:s==='[data-state-index]'?stateBox:null,createElement:s=>new Node(s),createElementNS:(ns,s)=>{const n=new Node(s);n.namespaceURI=ns;return n},getElementById:()=>null};
const base=require('path').resolve(__dirname,'..');const data=JSON.parse(fs.readFileSync(base+'/data/events.json'));const art=JSON.parse(fs.readFileSync(base+'/data/event-illustrations.json'));const metadata=JSON.parse(fs.readFileSync(base+'/data/event-filters.json'));for(const [name,values]of Object.entries({age:['','all-ages','children','teens','adults','families','unspecified'],access:['','sensory-friendly','wheelchair-step-free','adaptive-activities','caregiver-support','vision-support','hearing-support','unspecified']})){for(const value of values){const option=new Node('option');option.value=value;form.elements[name].append(option)}}
const context={document:doc,window:{listeners:{},addEventListener(k,f){this.listeners[k]=f},history:{replaceState(a,b,url){context.location.href=url}},matchMedia:()=>({matches:false})},location:{origin:'https://anausomelife.com',href:'https://anausomelife.com/calendar.html'},Intl,Date,URL,URLSearchParams,console,setTimeout:f=>f(),setInterval(){},requestAnimationFrame:f=>f(),fetch:async u=>({ok:true,json:async()=>u.includes('illustrations')?art:u.includes('event-filters')?metadata:data})};
vm.runInNewContext(fs.readFileSync(base+'/assets/events.js','utf8'),context);
function count(n,tag){return (n?.tagName===tag?1:0)+(n.children||[]).reduce((x,y)=>x+(typeof y==='object'?count(y,tag):0),0)}
setImmediate(()=>{try{const live=data.events.filter(e=>new Date(e.end)>new Date()&&!e.reviewRequired&&!['cancelled','review'].includes(e.status));assert.equal(map['.event-list'].children.length,live.length);assert.equal(map['.event-list'].children.filter(x=>count(x,'figure')>0).length,live.filter(e=>art.events[e.id]).length);assert.equal(stateBox.children.length,7);assert.equal(form.elements.month.children.length,3);for(const age of ['all-ages','children','teens','adults','families','unspecified']){form.elements.age.value=age;form.listeners.change();assert.equal(map['.event-list'].children.length,live.filter(e=>age==='unspecified'?!metadata.events[e.id].ageGroups.length:metadata.events[e.id].ageGroups.includes(age)).length,age)}form.elements.age.value='';
for(const access of ['sensory-friendly','wheelchair-step-free','adaptive-activities','caregiver-support','vision-support','hearing-support','unspecified']){form.elements.access.value=access;form.listeners.change();assert.equal(map['.event-list'].children.length,live.filter(e=>access==='unspecified'?!metadata.events[e.id].accessFeatures.length:metadata.events[e.id].accessFeatures.includes(access)).length,access)}form.elements.access.value='';
form.elements.age.value='teens';form.elements.access.value='vision-support';form.elements.state.value='MA';form.elements.month.value='2026-11';form.listeners.change();assert.deepEqual(map['.event-list'].children.map(c=>c.id),['event-carroll-cane-quest-2026-11-11']);
form.elements.age.value='';form.elements.access.value='';form.elements.state.value='';form.elements.month.value='';form.elements.format.value='Virtual';form.listeners.change();assert.equal(map['.event-list'].children.length,live.filter(e=>e.format==='Virtual').length);form.elements.format.value='';
form.elements.cost.value='free';form.listeners.change();assert.deepEqual(map['.event-list'].children.map(c=>c.id).sort(),live.filter(e=>e.costCategory==='free').map(e=>'event-'+e.id).sort());assert(!map['.event-list'].children.some(c=>c.id.startsWith('event-bcm-')||c.id.startsWith('event-cmnh-')),'Member-only discounts must not count as free admission');for(const state of ['CT','MA','ME','NH','RI','VT']){form.elements.state.value=state;form.listeners.change();assert(map['.event-list'].children.length>0,'Free dated listings in '+state)}form.elements.cost.value='';form.elements.state.value='';
form.elements.dateRange.value='weekend';form.listeners.change();assert(map['.event-list'].children.every(c=>{const e=live.find(e=>'event-'+e.id===c.id),day=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short'}).format(new Date(e.start));return day==='Sun'||day==='Sat'}),'Weekend results only');form.elements.dateRange.value='';
form.elements.month.value='2026-11';form.listeners.change();assert.equal(map['.event-list'].children.length,live.filter(e=>e.start.startsWith('2026-11')).length);form.elements.state.value='VT';form.listeners.change();assert.equal(map['.event-list'].children.length,live.filter(e=>e.start.startsWith('2026-11')&&e.state==='VT').length);form.elements.month.value='';form.elements.state.value='';form.elements.q.value='nutcracker';form.listeners.change();assert.equal(map['.event-list'].children.length,1);form.elements.q.value='zznonexistent';form.listeners.change();assert.equal(map['.event-list'].children.length,0);assert.equal(map['.event-empty'].hidden,false);form.elements.q.value='';form.elements.state.value='ME';form.elements.month.value='2026-11';form.elements.dateRange.value='';form.listeners.change();assert.equal(new URL(context.location.href).searchParams.get('state'),'ME');assert.equal(new URL(context.location.href).searchParams.get('month'),'2026-11');context.location.href='https://anausomelife.com/calendar.html?state=MA&age=teens&access=vision-support&month=2026-11&view=month';context.window.listeners.popstate();assert.equal(form.elements.state.value,'MA');assert.deepEqual(map['.event-list'].children.map(c=>c.id),['event-carroll-cane-quest-2026-11-11']);assert.equal(map['.event-month-view'].hidden,false);assert.equal(new URL(context.location.href).searchParams.get('view'),'month');
console.log('PASS: '+live.length+' active records; every age/access selection; combined age/access/state/month; virtual mode; current artwork subset; empty state.');}catch(e){console.error(e);process.exitCode=1}});
