const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners={};this.dataset={};this.attributes={};this.style={};this.clientWidth=640;this._text='';}set textContent(x){this._text=String(x);this.children=[]}get textContent(){return this._text+this.children.map(x=>typeof x==='string'?x:x.textContent).join('')}append(...xs){for(const x of xs){if(typeof x==='object')x.parent=this;this.children.push(x)}}prepend(...xs){for(const x of xs)if(typeof x==='object')x.parent=this;this.children.unshift(...xs)}replaceChildren(...xs){this.children=[];this._text='';this.append(...xs)}setAttribute(k,v){this.attributes[k]=String(v);if(k==='class')this.className=String(v)}addEventListener(k,f){this.listeners[k]=f}querySelector(s){return all(this,n=>s.startsWith('.')&&(n.className||'').split(' ').includes(s.slice(1)))[0]||null}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this)}scrollIntoView(){}focus(){this.focused=true}}
function all(n,f){return[n,...n.children.flatMap(c=>typeof c==='object'?all(c,f):[])].filter(f)}
const base=require('path').resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(base+'/data/event-locations.json')),events=JSON.parse(fs.readFileSync(base+'/data/events.json')).events.filter(e=>!e.reviewRequired&&e.status!=='cancelled'&&Date.parse(e.end)>Date.now());const groupCount=new Set(events.map(e=>e.venue+'|'+e.address)).size;
let resolve,fetchCount=0;const pending=new Promise(r=>resolve=r);const doc={currentScript:{src:'https://anausomelife.com/assets/event-map.js'},createElement:s=>new Node(s),createElementNS:(ns,s)=>new Node(s),createTextNode:s=>s,getElementById:()=>null};const ctx={document:doc,window:{matchMedia:()=>({matches:false})},location:{href:'https://anausomelife.com/calendar.html'},Intl,Date,URL,WeakMap,console,fetch:()=>{fetchCount++;return pending}};vm.runInNewContext(fs.readFileSync(base+'/assets/event-map.js','utf8'),ctx);
function cls(root,c){return all(root,n=>(n.className||'').split(' ').includes(c))}
(async()=>{const host=new Node();let selected;const one=ctx.window.AUsomeEventMap.render(host,events,id=>selected=id);const subset=events.filter(e=>e.state==='RI');const two=ctx.window.AUsomeEventMap.render(host,subset,id=>selected=id);resolve({ok:true,json:async()=>data});await Promise.all([one,two]);assert.equal(cls(host,'em-venue').length,new Set(subset.map(e=>e.venue+'|'+e.address)).size);assert.equal(cls(host,'em-event-link').length,subset.length);assert.equal(fetchCount,1);cls(host,'em-event-link')[0].listeners.click();assert(subset.some(e=>e.id===selected));await ctx.window.AUsomeEventMap.render(host,events,id=>selected=id);assert.equal(cls(host,'em-venue').length,groupCount);assert.equal(cls(host,'em-event-link').length,events.length);assert.equal(cls(host,'em-geography').length,1);const cluster=cls(host,'em-cluster')[0];assert(cluster);cluster.listeners.click();assert(cls(host,'em-venue').length<groupCount);assert.equal(cls(host,'em-geography').length,1);cls(host,'em-button')[0].listeners.click();assert.equal(cls(host,'em-venue').length,groupCount);for(const b of cls(host,'em-pin')){assert(parseFloat(b.style.left)>=0&&parseFloat(b.style.left)<=100);assert(b.attributes['aria-label'])}await ctx.window.AUsomeEventMap.render(host,[],()=>{});assert.equal(cls(host,'em-venue').length,0);assert.equal(cls(host,'em-empty').length,1);await ctx.window.AUsomeEventMap.render(host,[{id:'unmapped',title:'New venue',venue:'Unmapped',city:'Boston',state:'MA',address:'Test',start:'2026-12-01T10:00:00-05:00',sourceUrl:'javascript:bad()'}],()=>{});assert.equal(cls(host,'em-venue').length,1);assert.equal(cls(host,'em-pin').length,0);assert(!all(host,n=>n.href?.startsWith('javascript:')).length);await ctx.window.AUsomeEventMap.render(host,events.filter(e=>e.format==='Virtual'),()=>{});assert(cls(host,'em-map-column')[0].hidden);assert(!all(host,n=>n.href?.includes('google.com/maps')).length);assert(!cls(host,'em-location-note').length);console.log('PASS: stale async render guard; expanded event / venue counts; virtual-only no-directions view; selection callback; cluster zoom/reset; single basemap; empty state; unmapped venue fallback; HTTPS-only links.');})();
function escape(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}
function serialize(n){if(typeof n==='string')return escape(n);let a={...n.attributes};if(n.tagName==='svg')a.xmlns='http://www.w3.org/2000/svg';return '<'+n.tagName+' '+Object.entries(a).map(([k,v])=>k+'="'+escape(v)+'"').join(' ')+'>'+escape(n._text)+n.children.map(serialize).join('')+'</'+n.tagName+'>'}
